homeassistant:
  packages: !include_dir_named packages
  unit_system: metric
  time_zone: Europe/Berlin

frontend:
  themes: !include_dir_merge_named themes

default_config:
automation: !include automations.yaml
# https://www.home-assistant.io/integrations/maxcube/
maxcube:
  gateways:
    - host: 10.0.0.194

# https://www.home-assistant.io/integrations/sabnzbd/
sabnzbd:
  name: sabnzbd
  api_key: !secret sabnzbd_api_key
  host: 10.0.0.250
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size
